import { Api } from './api.js';
import { LocalDatabase } from './db.js';
import { SyncEngine } from './sync.js';
import type { Note, PdfDocument, Notebook } from './types.js';

const root = document.querySelector<HTMLElement>('#app')!;
let db: LocalDatabase; let engine: SyncEngine; let selectedNote: Note | null = null; let selectedPdf: PdfDocument | null = null; let selectedPdfUrl: string | null = null; let notebooks: Notebook[] = []; let busy = false; let message = ''; let error = '';

function state() { return engine.snapshot(); }
function esc(value: unknown) { return String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]!)); }
function setMessage(value = '') { message = value; error = ''; render(); }
function setError(value: unknown) { error = value instanceof Error ? value.message : String(value); message = ''; render(); }
async function act(action: () => Promise<void>) { if (busy) return; busy = true; render(); try { await action(); } catch (cause) { setError(cause); } finally { busy = false; render(); } }

function render(): void {
  const current = state(); const session = current.session;
  if (!session) { root.innerHTML = authTemplate(); bindAuth(); return; }
  const replica = current.replica; const offline = !navigator.onLine;
  root.innerHTML = `<div class="shell"><header><h1>SmartNotes</h1><div class="row"><span>${esc(session.displayName)}</span><button class="secondary" id="logout">Log out</button></div></header>
  <p class="status ${error ? 'error' : offline ? 'offline' : ''}">${esc(error || (busy ? 'Loading…' : offline ? `Offline — ${current.outbox.length} change(s) queued locally.` : message || (current.outbox.length ? `${current.outbox.length} change(s) waiting to sync.` : 'Synced.')))} ${!offline ? '<button class="secondary" id="sync">Sync now</button>' : ''}</p>
  <div class="grid"><aside class="panel stack"><strong>Notebooks</strong><div class="list">${notebooks.length ? notebooks.map(notebook => `<button data-notebook="${esc(notebook.id)}" class="${replica?.notebook.id === notebook.id ? 'selected' : ''}">${esc(notebook.title)}</button>`).join('') : '<p class="muted">No notebooks yet.</p>'}</div><form id="notebook-form" class="stack"><input name="title" required placeholder="New notebook" /><button>Create notebook</button></form></aside>
  <section class="panel">${replica ? workspaceTemplate(replica) : '<div class="empty">Create a notebook to start writing.</div>'}</section></div></div>`;
  bindApp();
}
function authTemplate() { return `<section class="auth panel stack"><h1>SmartNotes</h1><p class="muted">Your notes stay available offline and synchronize when you reconnect.</p><p class="status ${error ? 'error' : ''}">${esc(error || message)}</p><form id="auth" class="stack"><input name="name" placeholder="Display name (for signup)" /><input name="email" type="email" required placeholder="you@example.com" /><input name="password" type="password" required minlength="10" placeholder="Password (10+ characters)" /><div class="row"><button name="mode" value="login">Log in</button><button class="secondary" name="mode" value="signup">Sign up</button></div></form></section>`; }
function workspaceTemplate(replica: NonNullable<ReturnType<typeof state>['replica']>) { const notes = [...replica.notes].sort((a,b) => a.position - b.position); return `<div class="stack"><div class="row"><input id="notebook-title" value="${esc(replica.notebook.title)}" aria-label="Notebook title" /><button id="save-notebook" class="secondary">Rename</button><button id="delete-notebook" class="danger">Delete notebook</button><button id="new-note">New note</button><label class="secondary"><input id="pdf-upload" type="file" accept="application/pdf" hidden />Import PDF</label></div><div class="grid"><aside class="list">${notes.length ? notes.map((note, index) => `<div class="row note-row"><button data-note="${esc(note.id)}" class="${selectedNote?.id === note.id ? 'selected' : ''}">${esc(note.title || 'Untitled note')}</button><button data-move="${esc(note.id)}" data-direction="-1" aria-label="Move note up" ${index === 0 ? 'disabled' : ''}>↑</button><button data-move="${esc(note.id)}" data-direction="1" aria-label="Move note down" ${index === notes.length - 1 ? 'disabled' : ''}>↓</button></div>`).join('') : '<p class="muted">No notes yet.</p>'}<hr/>${replica.pdfs.map(pdf => `<button data-pdf="${esc(pdf.id)}">PDF: ${esc(pdf.filename)}</button>`).join('')}</aside><article>${selectedNote ? editorTemplate(selectedNote) : selectedPdf ? pdfTemplate(selectedPdf, replica) : '<div class="empty">Select or create a note.</div>'}</article></div></div>`; }
function editorTemplate(note: Note) { return `<div class="stack"><input id="note-title" value="${esc(note.title)}" aria-label="Note title" /><textarea id="note-body" aria-label="Note body">${esc(note.body)}</textarea><div class="row"><button id="save-note">Save locally</button><button id="delete-note" class="danger">Delete</button></div></div>`; }
function pdfTemplate(pdf: PdfDocument, replica: NonNullable<ReturnType<typeof state>['replica']>) { const annotations = replica.annotations.filter(annotation => annotation.pdfId === pdf.id); return `<div class="stack"><h3>${esc(pdf.filename)}</h3>${selectedPdfUrl ? `<object class="pdf" data="${esc(selectedPdfUrl)}" type="application/pdf">PDF preview unavailable.</object>` : '<p class="muted">Loading PDF…</p>'}<form id="annotation" class="row"><input name="text" required placeholder="Add an annotation" /><button>Add annotation</button></form><div class="stack"><strong>Annotations</strong>${annotations.length ? annotations.map(annotation => `<div class="row annotation"><span>${esc(annotation.text || annotation.kind)}</span><button data-delete-annotation="${esc(annotation.id)}" class="danger">Delete</button></div>`).join('') : '<p class="muted">No annotations yet.</p>'}</div></div>`; }

function bindAuth() { document.querySelector<HTMLFormElement>('#auth')!.addEventListener('submit', event => { event.preventDefault(); const submitter = (event as SubmitEvent).submitter as HTMLButtonElement; const form = new FormData(event.currentTarget as HTMLFormElement); act(async () => { const email = String(form.get('email')); const password = String(form.get('password')); const api = new Api(() => null); const response = submitter.value === 'signup' ? await api.signup(email, password, String(form.get('name'))) : await api.login(email, password); state().session = { token: response.token, email: response.user.email, displayName: response.user.displayName }; await engine.save(); setMessage('Welcome to SmartNotes.'); }); }); }
function bindApp() {
  document.querySelector('#logout')?.addEventListener('click', () => act(async () => { state().session = null; state().replica = null; state().outbox = []; selectedNote = null; await engine.save(); }));
  document.querySelector('#sync')?.addEventListener('click', () => act(async () => { await engine.sync(); setMessage(engine.conflictMessages().join(' ') || 'All changes synchronized.'); }));
  document.querySelectorAll<HTMLButtonElement>('[data-notebook]').forEach(button => button.addEventListener('click', () => act(async () => { await engine.chooseNotebook(button.dataset['notebook']!); selectedNote = null; selectedPdf = null; })));
  document.querySelector<HTMLFormElement>('#notebook-form')?.addEventListener('submit', event => { event.preventDefault(); const title = String(new FormData(event.currentTarget as HTMLFormElement).get('title')); act(async () => { await engine.addNotebook(title); notebooks = (await new Api(() => state().session).notebooks()).notebooks; selectedNote = null; setMessage('Notebook created.'); }); });
  document.querySelector('#save-notebook')?.addEventListener('click', () => act(async () => { const replica = state().replica!; const title = document.querySelector<HTMLInputElement>('#notebook-title')!.value.trim(); if (!title) throw new Error('A notebook needs a title.'); if (!navigator.onLine) { engine.queue('notebook', replica.notebook.id, { title, updatedAt: Date.now() }); await engine.save(); setMessage('Notebook rename saved locally.'); return; } const updated = await new Api(() => state().session).updateNotebook(replica.notebook.id, title); replica.notebook = updated.notebook; await engine.save(); notebooks = (await new Api(() => state().session).notebooks()).notebooks; setMessage('Notebook renamed.'); }));
  document.querySelector('#delete-notebook')?.addEventListener('click', () => act(async () => { const replica = state().replica!; if (!navigator.onLine) throw new Error('Notebook deletion needs a connection.'); await new Api(() => state().session).deleteNotebook(replica.notebook.id); notebooks = (await new Api(() => state().session).notebooks()).notebooks; state().replica = null; state().activeNotebookId = null; selectedNote = null; selectedPdf = null; await engine.save(); setMessage('Notebook deleted.'); }));
  document.querySelector('#new-note')?.addEventListener('click', () => act(async () => { const id = `note_${crypto.randomUUID().replaceAll('-', '')}`; const at = Date.now(); engine.queue('note', id, { title: 'Untitled note', body: '', position: at, createdAt: at, updatedAt: at }); selectedNote = state().replica!.notes.find(note => note.id === id)!; await engine.save(); setMessage('Note saved locally; it will sync automatically.'); }));
  document.querySelectorAll<HTMLButtonElement>('[data-note]').forEach(button => button.addEventListener('click', () => { selectedPdf = null; selectedNote = state().replica!.notes.find(note => note.id === button.dataset['note'])!; render(); }));
  document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(button => button.addEventListener('click', () => act(async () => { const replica = state().replica!; const ordered = [...replica.notes].sort((a, b) => a.position - b.position); const index = ordered.findIndex(note => note.id === button.dataset['move']); const other = ordered[index + Number(button.dataset['direction'])]; const note = ordered[index]; if (!note || !other) return; const at = Date.now(); engine.queue('note', note.id, { position: other.position, updatedAt: at }); engine.queue('note', other.id, { position: note.position, updatedAt: at }); await engine.save(); if (navigator.onLine) await engine.sync(); setMessage('Note reordered.'); })));
  document.querySelectorAll<HTMLButtonElement>('[data-pdf]').forEach(button => button.addEventListener('click', () => act(async () => { selectedNote = null; selectedPdf = state().replica!.pdfs.find(pdf => pdf.id === button.dataset['pdf'])!; if (selectedPdfUrl) URL.revokeObjectURL(selectedPdfUrl); if (navigator.onLine) { const view = await new Api(() => state().session).annotations(selectedPdf.id); state().replica!.annotations = [...state().replica!.annotations.filter(annotation => annotation.pdfId !== selectedPdf!.id), ...view.annotations]; await engine.save(); selectedPdfUrl = await new Api(() => state().session).pdfUrl(selectedPdf.id); } })));
  document.querySelector('#save-note')?.addEventListener('click', () => act(async () => { if (!selectedNote) return; const title = document.querySelector<HTMLInputElement>('#note-title')!.value; const body = document.querySelector<HTMLTextAreaElement>('#note-body')!.value; engine.queue('note', selectedNote.id, { title, body, updatedAt: Date.now() }); selectedNote = state().replica!.notes.find(note => note.id === selectedNote!.id)!; await engine.save(); if (navigator.onLine) await engine.sync(); setMessage('Note saved.'); }));
  document.querySelector('#delete-note')?.addEventListener('click', () => act(async () => { if (!selectedNote) return; engine.queue('note', selectedNote.id, {}, true); selectedNote = null; await engine.save(); if (navigator.onLine) await engine.sync(); setMessage('Note deleted.'); }));
  document.querySelector<HTMLInputElement>('#pdf-upload')?.addEventListener('change', event => { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (!file) return; act(async () => { if (!navigator.onLine) throw new Error('PDF import needs a connection; your existing notes can still be edited offline.'); const raw = new Uint8Array(await file.arrayBuffer()); let binary = ''; raw.forEach(byte => { binary += String.fromCharCode(byte); }); const pdf = await new Api(() => state().session).uploadPdf(state().replica!.notebook.id, file.name, btoa(binary)); state().replica!.pdfs.push(pdf.pdf); await engine.save(); selectedPdf = pdf.pdf; selectedNote = null; setMessage('PDF imported.'); }); });
  document.querySelector<HTMLFormElement>('#annotation')?.addEventListener('submit', event => { event.preventDefault(); if (!selectedPdf) return; const text = String(new FormData(event.currentTarget as HTMLFormElement).get('text')); act(async () => { const id = `anno_${crypto.randomUUID().replaceAll('-', '')}`; const at = Date.now(); engine.queue('annotation', id, { pdfId: selectedPdf!.id, page: 0, kind: 'note', rect: null, color: '#ffd60a', text, strokeId: null, createdAt: at, updatedAt: at }); await engine.save(); if (navigator.onLine) await engine.sync(); setMessage('Annotation saved locally and queued for synchronization.'); }); });
  document.querySelectorAll<HTMLButtonElement>('[data-delete-annotation]').forEach(button => button.addEventListener('click', () => act(async () => { engine.queue('annotation', button.dataset['deleteAnnotation']!, {}, true); await engine.save(); if (navigator.onLine) await engine.sync(); setMessage('Annotation deleted.'); })));
}

async function start() { db = await LocalDatabase.open(); let local: Awaited<ReturnType<LocalDatabase['read']>> | null = null; const api = new Api(() => local?.session ?? null); engine = new SyncEngine(db, api); local = await engine.load(); if (local.session && navigator.onLine) { try { notebooks = (await api.notebooks()).notebooks; } catch (cause) { error = cause instanceof Error ? cause.message : String(cause); } } window.addEventListener('online', () => { if (state().replica && state().outbox.length) void act(async () => { await engine.sync(); notebooks = (await api.notebooks()).notebooks; setMessage('Queued changes synchronized.'); }); else render(); }); window.addEventListener('offline', render); render(); }
void start().catch(setError);
