import { Api } from './api.js';
import { LocalDatabase } from './db.js';
import { SyncEngine } from './sync.js';
import type { Note, PdfDocument, Notebook } from './types.js';
import { escapeHtml as esc } from './ui/html.js';

const root = document.querySelector<HTMLElement>('#app')!;
let db: LocalDatabase, engine: SyncEngine, selectedNote: Note | null = null, selectedPdf: PdfDocument | null = null, selectedPdfUrl: string | null = null;
let notebooks: Notebook[] = [], busy = false, message = '', error = '';
type SaveState = 'idle' | 'dirty' | 'saving' | 'saved' | 'failed';
let saveState: SaveState = 'idle', saveDetail = 'No unsaved changes';
const state = () => engine.snapshot();
async function act(action: () => Promise<void>) { if (busy) return; busy = true; render(); try { await action(); error = ''; } catch (cause) { error = cause instanceof Error ? cause.message : String(cause); } finally { busy = false; render(); } }

function status() { const s = state(); if (error) return `<div class="app-status error" role="alert"><b>!</b><span><strong>Something went wrong.</strong> ${esc(error)}</span><button id="retry" class="text">Retry</button></div>`; if (busy) return `<div class="app-status" role="status"><i class="spinner"></i>Loading your notebook…</div>`; if (!navigator.onLine) return `<div class="app-status offline" role="status">⌁ Offline — ${s.outbox.length} change(s) safely stored on this device.</div>`; if (message || s.outbox.length) return `<div class="app-status" role="status">✓ ${esc(message || `${s.outbox.length} change(s) waiting to sync.`)}<button id="sync" class="text">Sync now</button></div>`; return ''; }
function render() {
  const s = state(); if (!s.session) { root.innerHTML = auth(); bindAuth(); return; }
  root.innerHTML = `<div class="shell"><header><a class="brand" href="#"><b>S</b>SmartNotes</a><div class="account"><span>${esc(s.session.displayName)}</span><button id="logout" class="secondary compact">Log out</button></div></header>${status()}<div class="app-layout"><aside class="notebooks panel"><h2>Notebooks</h2><nav>${notebooks.length ? notebooks.map(n => `<button data-notebook="${esc(n.id)}" class="nav ${s.replica?.notebook.id === n.id ? 'selected' : ''}"><span>▱</span><span class="truncate">${esc(n.title)}</span></button>`).join('') : '<p class="muted">No notebooks yet.</p>'}</nav><form id="notebook-form"><label class="sr-only" for="new-book">Notebook name</label><input id="new-book" name="title" required placeholder="Notebook name"><button>Create</button></form></aside><main class="workspace panel">${s.replica ? workspace(s.replica) : `<div class="blank"><i>＋</i><h2>Create a notebook</h2><p>Give your class notes a home, then add your first note.</p></div>`}</main></div></div>`; bindApp();
}
function auth() { return `<section class="auth panel"><div class="brand"><b>S</b>SmartNotes</div><h1>Your notes, ready when you are.</h1><p class="muted">Keep class notes available offline and synchronized across your devices.</p>${error ? `<p class="app-status error" role="alert">${esc(error)}</p>` : ''}<form id="auth"><label>Display name <span>(sign up only)</span><input name="name" autocomplete="name"></label><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required minlength="10" autocomplete="current-password"></label><div class="row"><button name="mode" value="login">Log in</button><button name="mode" value="signup" class="secondary">Sign up</button></div></form></section>`; }
function workspace(replica: NonNullable<ReturnType<typeof state>['replica']>) { const notes = [...replica.notes].sort((a,b) => a.position-b.position); return `<div class="workspace-inner ${selectedNote || selectedPdf ? 'show-detail' : ''}"><div class="toolbar"><div><input id="book-title" value="${esc(replica.notebook.title)}" aria-label="Notebook title"><button id="rename" class="secondary compact">Rename</button></div><div><label class="secondary compact upload"><input id="pdf-upload" type="file" accept="application/pdf" hidden>Import PDF</label><button id="delete-book" class="danger text compact">Delete notebook</button></div></div><div class="notes-layout"><aside class="note-rail"><div class="rail-head"><div><small>Current notebook</small><h2 id="notes-heading" tabindex="-1">Notes</h2></div><button id="new-note">＋ New note</button></div><div class="note-list" role="list">${notes.length ? notes.map((n,i) => noteRow(n,i,notes.length)).join('') : `<div class="empty-list"><i>✎</i><h3>Create your first note</h3><p>Start with a lecture, reading, or idea you want to remember.</p><button id="empty-new">＋ New note</button></div>`}${replica.pdfs.length ? `<section class="pdf-list"><small>PDFs</small>${replica.pdfs.map(p => `<button data-pdf="${esc(p.id)}">▤ <span class="truncate">${esc(p.filename)}</span></button>`).join('')}</section>` : ''}</div></aside><article class="editor-pane">${selectedNote ? editor(selectedNote) : selectedPdf ? pdfView(selectedPdf, replica) : `<div class="blank"><i>↖</i><h2>Select a note</h2><p>Choose a note from the list, or create a new one to begin writing.</p></div>`}</article></div></div>`; }
function noteRow(note: Note, i: number, count: number) { return `<div class="note-row ${selectedNote?.id === note.id ? 'selected' : ''}" role="listitem"><button data-note="${esc(note.id)}" class="note-open"><strong>${esc(note.title || 'Untitled note')}</strong><span>${new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(note.updatedAt)}</span></button><div class="moves"><button data-move="${esc(note.id)}" data-direction="-1" aria-label="Move note up" ${i===0?'disabled':''}>↑</button><button data-move="${esc(note.id)}" data-direction="1" aria-label="Move note down" ${i===count-1?'disabled':''}>↓</button></div></div>`; }
function saveStatus() { const icon = saveState === 'saving' ? '<i class="spinner"></i>' : saveState === 'failed' ? '!' : saveState === 'saved' ? '✓' : '●'; return `<div id="save-status" class="save-status ${saveState}" role="status" aria-live="polite">${icon}<span>${esc(saveDetail)}</span></div>`; }
function editor(note: Note) { return `<div class="editor"><div class="editor-top"><button id="back" class="back">← Notes</button>${saveStatus()}<div class="editor-actions"><button id="save-note">Save note</button><button id="delete-note" class="danger text">Delete</button></div></div><label class="sr-only" for="note-title">Note title</label><input id="note-title" class="editor-title" value="${esc(note.title)}" placeholder="Untitled note"><label class="sr-only" for="note-body">Note body</label><textarea id="note-body" class="editor-body" placeholder="Start writing…">${esc(note.body)}</textarea></div>`; }
function pdfView(pdf: PdfDocument, replica: NonNullable<ReturnType<typeof state>['replica']>) { const annotations = replica.annotations.filter(a=>a.pdfId===pdf.id); return `<div class="pdf-editor"><div class="editor-top"><button id="back" class="back">← Notes</button><h2 class="truncate">${esc(pdf.filename)}</h2></div>${selectedPdfUrl ? `<object class="pdf" data="${esc(selectedPdfUrl)}" type="application/pdf">PDF preview unavailable.</object>` : '<div class="loading"><i class="spinner"></i>Loading PDF…</div>'}<form id="annotation" class="row"><input name="text" aria-label="Annotation" required placeholder="Add an annotation"><button>Add</button></form><section class="annotations"><h3>Annotations</h3>${annotations.length ? annotations.map(a=>`<div class="annotation"><span>${esc(a.text||a.kind)}</span><button data-delete-annotation="${esc(a.id)}" class="danger text">Delete</button></div>`).join(''):'<p class="muted">No annotations yet.</p>'}</section></div>`; }

function bindAuth() { document.querySelector<HTMLFormElement>('#auth')!.addEventListener('submit', e => { e.preventDefault(); const submitter=(e as SubmitEvent).submitter as HTMLButtonElement, form=new FormData(e.currentTarget as HTMLFormElement); act(async()=>{const api=new Api(()=>null), result=submitter.value==='signup'?await api.signup(String(form.get('email')),String(form.get('password')),String(form.get('name'))):await api.login(String(form.get('email')),String(form.get('password'))); state().session={token:result.token,email:result.user.email,displayName:result.user.displayName}; await engine.save(); message='Welcome to SmartNotes.';});}); }
function bindApp() {
  document.querySelector('#retry')?.addEventListener('click',()=>{error='';void loadNotebooks();}); document.querySelector('#logout')?.addEventListener('click',()=>act(async()=>{state().session=null;state().replica=null;state().outbox=[];selectedNote=null;await engine.save();})); document.querySelector('#sync')?.addEventListener('click',()=>act(async()=>{await engine.sync();message=engine.conflictMessages().join(' ')||'All changes synchronized.';}));
  document.querySelectorAll<HTMLButtonElement>('[data-notebook]').forEach(b=>b.addEventListener('click',()=>act(async()=>{await engine.chooseNotebook(b.dataset['notebook']!);selectedNote=null;selectedPdf=null;}))); document.querySelector<HTMLFormElement>('#notebook-form')?.addEventListener('submit',e=>{e.preventDefault();const title=String(new FormData(e.currentTarget as HTMLFormElement).get('title'));act(async()=>{await engine.addNotebook(title);notebooks=(await new Api(()=>state().session).notebooks()).notebooks;message='Notebook created.';});});
  document.querySelector('#rename')?.addEventListener('click',()=>act(async()=>{const r=state().replica!,title=document.querySelector<HTMLInputElement>('#book-title')!.value.trim();if(!title)throw new Error('A notebook needs a title.');if(!navigator.onLine){engine.queue('notebook',r.notebook.id,{title,updatedAt:Date.now()});await engine.save();message='Notebook rename saved on this device.';return;}r.notebook=(await new Api(()=>state().session).updateNotebook(r.notebook.id,title)).notebook;await engine.save();notebooks=(await new Api(()=>state().session).notebooks()).notebooks;message='Notebook renamed.';}));
  document.querySelector('#delete-book')?.addEventListener('click',()=>act(async()=>{const r=state().replica!;if(!navigator.onLine)throw new Error('Notebook deletion needs a connection.');await new Api(()=>state().session).deleteNotebook(r.notebook.id);notebooks=(await new Api(()=>state().session).notebooks()).notebooks;state().replica=null;state().activeNotebookId=null;selectedNote=selectedPdf=null;await engine.save();message='Notebook deleted.';}));
  const create=()=>act(async()=>{const id=`note_${crypto.randomUUID().replaceAll('-','')}`,at=Date.now();engine.queue('note',id,{title:'Untitled note',body:'',position:at,createdAt:at,updatedAt:at});selectedNote=state().replica!.notes.find(n=>n.id===id)!;selectedPdf=null;saveState='dirty';saveDetail='Not saved to server yet';await engine.save();message='';queueMicrotask(()=>document.querySelector<HTMLInputElement>('#note-title')?.select());}); document.querySelector('#new-note')?.addEventListener('click',create);document.querySelector('#empty-new')?.addEventListener('click',create);
  document.querySelectorAll<HTMLButtonElement>('[data-note]').forEach(b=>b.addEventListener('click',()=>{selectedPdf=null;selectedNote=state().replica!.notes.find(n=>n.id===b.dataset['note'])!;saveState='idle';saveDetail='No unsaved changes';render();})); document.querySelector('#back')?.addEventListener('click',()=>{selectedNote=selectedPdf=null;render();document.querySelector<HTMLElement>('#notes-heading')?.focus();});
  document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>b.addEventListener('click',()=>act(async()=>{const ordered=[...state().replica!.notes].sort((a,c)=>a.position-c.position),i=ordered.findIndex(n=>n.id===b.dataset['move']),other=ordered[i+Number(b.dataset['direction'])],note=ordered[i];if(!note||!other)return;const at=Date.now();engine.queue('note',note.id,{position:other.position,updatedAt:at});engine.queue('note',other.id,{position:note.position,updatedAt:at});await engine.save();if(navigator.onLine)await engine.sync();message='Note reordered.';})));
  document.querySelectorAll<HTMLButtonElement>('[data-pdf]').forEach(b=>b.addEventListener('click',()=>act(async()=>{selectedNote=null;selectedPdf=state().replica!.pdfs.find(p=>p.id===b.dataset['pdf'])!;if(selectedPdfUrl)URL.revokeObjectURL(selectedPdfUrl);if(navigator.onLine){const api=new Api(()=>state().session),view=await api.annotations(selectedPdf.id);state().replica!.annotations=[...state().replica!.annotations.filter(a=>a.pdfId!==selectedPdf!.id),...view.annotations];await engine.save();selectedPdfUrl=await api.pdfUrl(selectedPdf.id);}})));
  bindEditor(); bindPdf();
}
function updateSave(next: SaveState, detail: string) { saveState=next;saveDetail=detail;const old=document.querySelector('#save-status');if(!old)return;const h=document.createElement('div');h.innerHTML=saveStatus();old.replaceWith(h.firstElementChild!); }
function bindEditor(){const title=document.querySelector('#note-title'),body=document.querySelector('#note-body');[title,body].forEach(c=>c?.addEventListener('input',()=>updateSave('dirty','Unsaved changes')));document.querySelector('#save-note')?.addEventListener('click',()=>void saveNote());document.querySelector('#delete-note')?.addEventListener('click',()=>act(async()=>{if(!selectedNote)return;engine.queue('note',selectedNote.id,{},true);selectedNote=null;await engine.save();if(navigator.onLine)await engine.sync();message='Note deleted.';}));}
async function saveNote(){if(!selectedNote||saveState==='saving')return;const title=document.querySelector<HTMLInputElement>('#note-title')!.value,body=document.querySelector<HTMLTextAreaElement>('#note-body')!.value;updateSave('saving','Saving…');try{engine.queue('note',selectedNote.id,{title,body,updatedAt:Date.now()});selectedNote=state().replica!.notes.find(n=>n.id===selectedNote!.id)!;await engine.save();if(!navigator.onLine){updateSave('dirty','Saved on this device — waiting for connection');return;}if(new URLSearchParams(location.search).get('failSaves')==='1')throw new Error('The server could not save this note. Your draft is still here.');await engine.sync();if(engine.conflictMessages().length)throw new Error(engine.conflictMessages().join(' '));updateSave('saved','Saved to server');}catch(cause){updateSave('failed',cause instanceof Error?cause.message:'Save failed. Your draft is still here.');}}
function bindPdf(){document.querySelector<HTMLInputElement>('#pdf-upload')?.addEventListener('change',e=>{const file=(e.currentTarget as HTMLInputElement).files?.[0];if(!file)return;act(async()=>{if(!navigator.onLine)throw new Error('PDF import needs a connection.');const raw=new Uint8Array(await file.arrayBuffer());let binary='';raw.forEach(byte=>binary+=String.fromCharCode(byte));const pdf=(await new Api(()=>state().session).uploadPdf(state().replica!.notebook.id,file.name,btoa(binary))).pdf;state().replica!.pdfs.push(pdf);await engine.save();selectedPdf=pdf;selectedNote=null;message='PDF imported.';});});document.querySelector<HTMLFormElement>('#annotation')?.addEventListener('submit',e=>{e.preventDefault();if(!selectedPdf)return;const text=String(new FormData(e.currentTarget as HTMLFormElement).get('text'));act(async()=>{const id=`anno_${crypto.randomUUID().replaceAll('-','')}`,at=Date.now();engine.queue('annotation',id,{pdfId:selectedPdf!.id,page:0,kind:'note',rect:null,color:'#ffd60a',text,strokeId:null,createdAt:at,updatedAt:at});await engine.save();if(navigator.onLine)await engine.sync();message='Annotation saved and synchronized.';});});document.querySelectorAll<HTMLButtonElement>('[data-delete-annotation]').forEach(b=>b.addEventListener('click',()=>act(async()=>{engine.queue('annotation',b.dataset['deleteAnnotation']!,{},true);await engine.save();if(navigator.onLine)await engine.sync();message='Annotation deleted.';})));}
async function loadNotebooks(){busy=true;render();try{notebooks=(await new Api(()=>state().session).notebooks()).notebooks;error='';}catch(cause){error=cause instanceof Error?cause.message:String(cause);}finally{busy=false;render();}}
async function start(){db=await LocalDatabase.open();let local:Awaited<ReturnType<LocalDatabase['read']>>|null=null;const api=new Api(()=>local?.session??null);engine=new SyncEngine(db,api);local=await engine.load();if(local.session&&navigator.onLine)await loadNotebooks();window.addEventListener('online',()=>{if(state().replica&&state().outbox.length)void act(async()=>{await engine.sync();notebooks=(await api.notebooks()).notebooks;message='Queued changes synchronized.';});else render();});window.addEventListener('offline',render);render();}
void start().catch(cause=>{error=cause instanceof Error?cause.message:String(cause);render();});
